test: test install script

diff --git a/test b/test
--- a/test
+++ b/test
@@ -1,12 +1,19 @@
 #!/usr/bin/env bash
 main() {
   set -e
+  TEST_DIR="$(mktemp -d)"
+
+  echo "==> Testing install"
+  export INSTALL_DIR="$TEST_DIR/bin"
+  mkdir -p $INSTALL_DIR
+  ./install
+  assert_exists "$INSTALL_DIR/git-get" "git-get was installed"
 
   echo "==> Testing git-get"
-  GIT_PATH="$(pwd)/test-repos"
+  GIT_PATH="$TEST_DIR/repos"
   rm -rf $GIT_PATH
   mkdir -p $GIT_PATH
-  cd "$(GIT_PATH=$GIT_PATH ./git-get https://github.com/pietvanzoen/git-get.git)"
+  cd "$(GIT_PATH=$GIT_PATH $INSTALL_DIR/git-get https://github.com/pietvanzoen/git-get.git)"
 
   assert_equal $(pwd) "$GIT_PATH/github.com/pietvanzoen/git-get" "sets correct repo path"
 }
@@ -19,6 +26,15 @@ assert_equal () {
     exit 1
   fi
   echo "PASS: $3"
+}
+
+assert_exists() {
+  if ! [[ -s "$1" ]]; then
+    echo "FAIL: $2"
+    echo -e "  expected $1 to exist with a size greater than zero"
+    exit 1
+  fi
+  echo "PASS: $2"
 }
 
 main
